#![allow(clippy::too_many_lines)]
use gooey_core::events::{
    Key, KeyCode, KeyEvent, KeyLocation, ModifierKeys, ModifierState, Modifiers, NativeKey, NativeKeyCode,
};
use kludgine::app::winit::keyboard::ModifiersKeyState;

mod winit {
    pub use kludgine::app::winit::event::*;
    pub use kludgine::app::winit::keyboard::*;
}


#[must_use]
pub fn map_input_event(
    winit::KeyEvent {
        physical_key,
        logical_key,
        text,
        location,
        repeat,
        ..
    }: winit::KeyEvent,
    modifiers: winit::Modifiers,
) -> KeyEvent {
    KeyEvent {
        physical_key: map_key_code(physical_key),
        logical_key: map_key(logical_key),
        text,
        location: map_key_location(location),
        repeat,
        modifiers: map_modifiers(modifiers),
    }
}

fn map_key_code(physical_key: winit::KeyCode) -> KeyCode {
    match physical_key {
        winit::KeyCode::Unidentified(u) => KeyCode::Unidentified(map_native_key_code(u)),
        winit::KeyCode::Backquote => KeyCode::Backquote,
        winit::KeyCode::Backslash => KeyCode::Backslash,
        winit::KeyCode::BracketLeft => KeyCode::BracketLeft,
        winit::KeyCode::BracketRight => KeyCode::BracketRight,
        winit::KeyCode::Comma => KeyCode::Comma,
        winit::KeyCode::Digit0 => KeyCode::Digit0,
        winit::KeyCode::Digit1 => KeyCode::Digit1,
        winit::KeyCode::Digit2 => KeyCode::Digit2,
        winit::KeyCode::Digit3 => KeyCode::Digit3,
        winit::KeyCode::Digit4 => KeyCode::Digit4,
        winit::KeyCode::Digit5 => KeyCode::Digit5,
        winit::KeyCode::Digit6 => KeyCode::Digit6,
        winit::KeyCode::Digit7 => KeyCode::Digit7,
        winit::KeyCode::Digit8 => KeyCode::Digit8,
        winit::KeyCode::Digit9 => KeyCode::Digit9,
        winit::KeyCode::Equal => KeyCode::Equal,
        winit::KeyCode::IntlBackslash => KeyCode::IntlBackslash,
        winit::KeyCode::IntlRo => KeyCode::IntlRo,
        winit::KeyCode::IntlYen => KeyCode::IntlYen,
        winit::KeyCode::KeyA => KeyCode::KeyA,
        winit::KeyCode::KeyB => KeyCode::KeyB,
        winit::KeyCode::KeyC => KeyCode::KeyC,
        winit::KeyCode::KeyD => KeyCode::KeyD,
        winit::KeyCode::KeyE => KeyCode::KeyE,
        winit::KeyCode::KeyF => KeyCode::KeyF,
        winit::KeyCode::KeyG => KeyCode::KeyG,
        winit::KeyCode::KeyH => KeyCode::KeyH,
        winit::KeyCode::KeyI => KeyCode::KeyI,
        winit::KeyCode::KeyJ => KeyCode::KeyJ,
        winit::KeyCode::KeyK => KeyCode::KeyK,
        winit::KeyCode::KeyL => KeyCode::KeyL,
        winit::KeyCode::KeyM => KeyCode::KeyM,
        winit::KeyCode::KeyN => KeyCode::KeyN,
        winit::KeyCode::KeyO => KeyCode::KeyO,
        winit::KeyCode::KeyP => KeyCode::KeyP,
        winit::KeyCode::KeyQ => KeyCode::KeyQ,
        winit::KeyCode::KeyR => KeyCode::KeyR,
        winit::KeyCode::KeyS => KeyCode::KeyS,
        winit::KeyCode::KeyT => KeyCode::KeyT,
        winit::KeyCode::KeyU => KeyCode::KeyU,
        winit::KeyCode::KeyV => KeyCode::KeyV,
        winit::KeyCode::KeyW => KeyCode::KeyW,
        winit::KeyCode::KeyX => KeyCode::KeyX,
        winit::KeyCode::KeyY => KeyCode::KeyY,
        winit::KeyCode::KeyZ => KeyCode::KeyZ,
        winit::KeyCode::Minus => KeyCode::Minus,
        winit::KeyCode::Period => KeyCode::Period,
        winit::KeyCode::Quote => KeyCode::Quote,
        winit::KeyCode::Semicolon => KeyCode::Semicolon,
        winit::KeyCode::Slash => KeyCode::Slash,
        winit::KeyCode::AltLeft => KeyCode::AltLeft,
        winit::KeyCode::AltRight => KeyCode::AltRight,
        winit::KeyCode::Backspace => KeyCode::Backspace,
        winit::KeyCode::CapsLock => KeyCode::CapsLock,
        winit::KeyCode::ContextMenu => KeyCode::ContextMenu,
        winit::KeyCode::ControlLeft => KeyCode::ControlLeft,
        winit::KeyCode::ControlRight => KeyCode::ControlRight,
        winit::KeyCode::Enter => KeyCode::Enter,
        winit::KeyCode::SuperLeft => KeyCode::SuperLeft,
        winit::KeyCode::SuperRight => KeyCode::SuperRight,
        winit::KeyCode::ShiftLeft => KeyCode::ShiftLeft,
        winit::KeyCode::ShiftRight => KeyCode::ShiftRight,
        winit::KeyCode::Space => KeyCode::Space,
        winit::KeyCode::Tab => KeyCode::Tab,
        winit::KeyCode::Convert => KeyCode::Convert,
        winit::KeyCode::KanaMode => KeyCode::KanaMode,
        winit::KeyCode::Lang1 => KeyCode::Lang1,
        winit::KeyCode::Lang2 => KeyCode::Lang2,
        winit::KeyCode::Lang3 => KeyCode::Lang3,
        winit::KeyCode::Lang4 => KeyCode::Lang4,
        winit::KeyCode::Lang5 => KeyCode::Lang5,
        winit::KeyCode::NonConvert => KeyCode::NonConvert,
        winit::KeyCode::Delete => KeyCode::Delete,
        winit::KeyCode::End => KeyCode::End,
        winit::KeyCode::Help => KeyCode::Help,
        winit::KeyCode::Home => KeyCode::Home,
        winit::KeyCode::Insert => KeyCode::Insert,
        winit::KeyCode::PageDown => KeyCode::PageDown,
        winit::KeyCode::PageUp => KeyCode::PageUp,
        winit::KeyCode::ArrowDown => KeyCode::ArrowDown,
        winit::KeyCode::ArrowLeft => KeyCode::ArrowLeft,
        winit::KeyCode::ArrowRight => KeyCode::ArrowRight,
        winit::KeyCode::ArrowUp => KeyCode::ArrowUp,
        winit::KeyCode::NumLock => KeyCode::NumLock,
        winit::KeyCode::Numpad0 => KeyCode::Numpad0,
        winit::KeyCode::Numpad1 => KeyCode::Numpad1,
        winit::KeyCode::Numpad2 => KeyCode::Numpad2,
        winit::KeyCode::Numpad3 => KeyCode::Numpad3,
        winit::KeyCode::Numpad4 => KeyCode::Numpad4,
        winit::KeyCode::Numpad5 => KeyCode::Numpad5,
        winit::KeyCode::Numpad6 => KeyCode::Numpad6,
        winit::KeyCode::Numpad7 => KeyCode::Numpad7,
        winit::KeyCode::Numpad8 => KeyCode::Numpad8,
        winit::KeyCode::Numpad9 => KeyCode::Numpad9,
        winit::KeyCode::NumpadAdd => KeyCode::NumpadAdd,
        winit::KeyCode::NumpadBackspace => KeyCode::NumpadBackspace,
        winit::KeyCode::NumpadClear => KeyCode::NumpadClear,
        winit::KeyCode::NumpadClearEntry => KeyCode::NumpadClearEntry,
        winit::KeyCode::NumpadComma => KeyCode::NumpadComma,
        winit::KeyCode::NumpadDecimal => KeyCode::NumpadDecimal,
        winit::KeyCode::NumpadDivide => KeyCode::NumpadDivide,
        winit::KeyCode::NumpadEnter => KeyCode::NumpadEnter,
        winit::KeyCode::NumpadEqual => KeyCode::NumpadEqual,
        winit::KeyCode::NumpadHash => KeyCode::NumpadHash,
        winit::KeyCode::NumpadMemoryAdd => KeyCode::NumpadMemoryAdd,
        winit::KeyCode::NumpadMemoryClear => KeyCode::NumpadMemoryClear,
        winit::KeyCode::NumpadMemoryRecall => KeyCode::NumpadMemoryRecall,
        winit::KeyCode::NumpadMemoryStore => KeyCode::NumpadMemoryStore,
        winit::KeyCode::NumpadMemorySubtract => KeyCode::NumpadMemorySubtract,
        winit::KeyCode::NumpadMultiply => KeyCode::NumpadMultiply,
        winit::KeyCode::NumpadParenLeft => KeyCode::NumpadParenLeft,
        winit::KeyCode::NumpadParenRight => KeyCode::NumpadParenRight,
        winit::KeyCode::NumpadStar => KeyCode::NumpadStar,
        winit::KeyCode::NumpadSubtract => KeyCode::NumpadSubtract,
        winit::KeyCode::Escape => KeyCode::Escape,
        winit::KeyCode::Fn => KeyCode::Fn,
        winit::KeyCode::FnLock => KeyCode::FnLock,
        winit::KeyCode::PrintScreen => KeyCode::PrintScreen,
        winit::KeyCode::ScrollLock => KeyCode::ScrollLock,
        winit::KeyCode::Pause => KeyCode::Pause,
        winit::KeyCode::BrowserBack => KeyCode::BrowserBack,
        winit::KeyCode::BrowserFavorites => KeyCode::BrowserFavorites,
        winit::KeyCode::BrowserForward => KeyCode::BrowserForward,
        winit::KeyCode::BrowserHome => KeyCode::BrowserHome,
        winit::KeyCode::BrowserRefresh => KeyCode::BrowserRefresh,
        winit::KeyCode::BrowserSearch => KeyCode::BrowserSearch,
        winit::KeyCode::BrowserStop => KeyCode::BrowserStop,
        winit::KeyCode::Eject => KeyCode::Eject,
        winit::KeyCode::LaunchApp1 => KeyCode::LaunchApp1,
        winit::KeyCode::LaunchApp2 => KeyCode::LaunchApp2,
        winit::KeyCode::LaunchMail => KeyCode::LaunchMail,
        winit::KeyCode::MediaPlayPause => KeyCode::MediaPlayPause,
        winit::KeyCode::MediaSelect => KeyCode::MediaSelect,
        winit::KeyCode::MediaStop => KeyCode::MediaStop,
        winit::KeyCode::MediaTrackNext => KeyCode::MediaTrackNext,
        winit::KeyCode::MediaTrackPrevious => KeyCode::MediaTrackPrevious,
        winit::KeyCode::Power => KeyCode::Power,
        winit::KeyCode::Sleep => KeyCode::Sleep,
        winit::KeyCode::AudioVolumeDown => KeyCode::AudioVolumeDown,
        winit::KeyCode::AudioVolumeMute => KeyCode::AudioVolumeMute,
        winit::KeyCode::AudioVolumeUp => KeyCode::AudioVolumeUp,
        winit::KeyCode::WakeUp => KeyCode::WakeUp,
        winit::KeyCode::Meta => KeyCode::Meta,
        winit::KeyCode::Hyper => KeyCode::Hyper,
        winit::KeyCode::Turbo => KeyCode::Turbo,
        winit::KeyCode::Abort => KeyCode::Abort,
        winit::KeyCode::Resume => KeyCode::Resume,
        winit::KeyCode::Suspend => KeyCode::Suspend,
        winit::KeyCode::Again => KeyCode::Again,
        winit::KeyCode::Copy => KeyCode::Copy,
        winit::KeyCode::Cut => KeyCode::Cut,
        winit::KeyCode::Find => KeyCode::Find,
        winit::KeyCode::Open => KeyCode::Open,
        winit::KeyCode::Paste => KeyCode::Paste,
        winit::KeyCode::Props => KeyCode::Props,
        winit::KeyCode::Select => KeyCode::Select,
        winit::KeyCode::Undo => KeyCode::Undo,
        winit::KeyCode::Hiragana => KeyCode::Hiragana,
        winit::KeyCode::Katakana => KeyCode::Katakana,
        winit::KeyCode::F1 => KeyCode::F1,
        winit::KeyCode::F2 => KeyCode::F2,
        winit::KeyCode::F3 => KeyCode::F3,
        winit::KeyCode::F4 => KeyCode::F4,
        winit::KeyCode::F5 => KeyCode::F5,
        winit::KeyCode::F6 => KeyCode::F6,
        winit::KeyCode::F7 => KeyCode::F7,
        winit::KeyCode::F8 => KeyCode::F8,
        winit::KeyCode::F9 => KeyCode::F9,
        winit::KeyCode::F10 => KeyCode::F10,
        winit::KeyCode::F11 => KeyCode::F11,
        winit::KeyCode::F12 => KeyCode::F12,
        winit::KeyCode::F13 => KeyCode::F13,
        winit::KeyCode::F14 => KeyCode::F14,
        winit::KeyCode::F15 => KeyCode::F15,
        winit::KeyCode::F16 => KeyCode::F16,
        winit::KeyCode::F17 => KeyCode::F17,
        winit::KeyCode::F18 => KeyCode::F18,
        winit::KeyCode::F19 => KeyCode::F19,
        winit::KeyCode::F20 => KeyCode::F20,
        winit::KeyCode::F21 => KeyCode::F21,
        winit::KeyCode::F22 => KeyCode::F22,
        winit::KeyCode::F23 => KeyCode::F23,
        winit::KeyCode::F24 => KeyCode::F24,
        winit::KeyCode::F25 => KeyCode::F25,
        winit::KeyCode::F26 => KeyCode::F26,
        winit::KeyCode::F27 => KeyCode::F27,
        winit::KeyCode::F28 => KeyCode::F28,
        winit::KeyCode::F29 => KeyCode::F29,
        winit::KeyCode::F30 => KeyCode::F30,
        winit::KeyCode::F31 => KeyCode::F31,
        winit::KeyCode::F32 => KeyCode::F32,
        winit::KeyCode::F33 => KeyCode::F33,
        winit::KeyCode::F34 => KeyCode::F34,
        winit::KeyCode::F35 => KeyCode::F35,
        _ => todo!(),
    }
}

fn map_native_key_code(key_code: winit::NativeKeyCode) -> NativeKeyCode {
    match key_code {
        winit::NativeKeyCode::Unidentified => NativeKeyCode::Unidentified ,
        winit::NativeKeyCode::Android(k) => NativeKeyCode::Android(k) ,
        winit::NativeKeyCode::MacOS(k) => NativeKeyCode::MacOS(k) ,
        winit::NativeKeyCode::Windows(k) => NativeKeyCode::Windows(k) ,
        winit::NativeKeyCode::Xkb(k) => NativeKeyCode::Xkb(k) ,
    }
}

fn map_key(logical_key: winit::Key) -> Key {
    match logical_key {
        winit::Key::Character(c) => Key::Character(c),
        winit::Key::Unidentified(u) => Key::Unidentified(map_native_key(u)),
        winit::Key::Dead(d) => Key::Dead(d),
        winit::Key::Alt => Key::Alt,
        winit::Key::AltGraph => Key::AltGraph,
        winit::Key::CapsLock => Key::CapsLock,
        winit::Key::Control => Key::Control,
        winit::Key::Fn => Key::Fn,
        winit::Key::FnLock => Key::FnLock,
        winit::Key::NumLock => Key::NumLock,
        winit::Key::ScrollLock => Key::ScrollLock,
        winit::Key::Shift => Key::Shift,
        winit::Key::Symbol => Key::Symbol,
        winit::Key::SymbolLock => Key::SymbolLock,
        winit::Key::Meta => Key::Meta,
        winit::Key::Hyper => Key::Hyper,
        winit::Key::Super => Key::Super,
        winit::Key::Enter => Key::Enter,
        winit::Key::Tab => Key::Tab,
        winit::Key::Space => Key::Space,
        winit::Key::ArrowDown => Key::ArrowDown,
        winit::Key::ArrowLeft => Key::ArrowLeft,
        winit::Key::ArrowRight => Key::ArrowRight,
        winit::Key::ArrowUp => Key::ArrowUp,
        winit::Key::End => Key::End,
        winit::Key::Home => Key::Home,
        winit::Key::PageDown => Key::PageDown,
        winit::Key::PageUp => Key::PageUp,
        winit::Key::Backspace => Key::Backspace,
        winit::Key::Clear => Key::Clear,
        winit::Key::Copy => Key::Copy,
        winit::Key::CrSel => Key::CrSel,
        winit::Key::Cut => Key::Cut,
        winit::Key::Delete => Key::Delete,
        winit::Key::EraseEof => Key::EraseEof,
        winit::Key::ExSel => Key::ExSel,
        winit::Key::Insert => Key::Insert,
        winit::Key::Paste => Key::Paste,
        winit::Key::Redo => Key::Redo,
        winit::Key::Undo => Key::Undo,
        winit::Key::Accept => Key::Accept,
        winit::Key::Again => Key::Again,
        winit::Key::Attn => Key::Attn,
        winit::Key::Cancel => Key::Cancel,
        winit::Key::ContextMenu => Key::ContextMenu,
        winit::Key::Escape => Key::Escape,
        winit::Key::Execute => Key::Execute,
        winit::Key::Find => Key::Find,
        winit::Key::Help => Key::Help,
        winit::Key::Pause => Key::Pause,
        winit::Key::Play => Key::Play,
        winit::Key::Props => Key::Props,
        winit::Key::Select => Key::Select,
        winit::Key::ZoomIn => Key::ZoomIn,
        winit::Key::ZoomOut => Key::ZoomOut,
        winit::Key::BrightnessDown => Key::BrightnessDown,
        winit::Key::BrightnessUp => Key::BrightnessUp,
        winit::Key::Eject => Key::Eject,
        winit::Key::LogOff => Key::LogOff,
        winit::Key::Power => Key::Power,
        winit::Key::PowerOff => Key::PowerOff,
        winit::Key::PrintScreen => Key::PrintScreen,
        winit::Key::Hibernate => Key::Hibernate,
        winit::Key::Standby => Key::Standby,
        winit::Key::WakeUp => Key::WakeUp,
        winit::Key::AllCandidates => Key::AllCandidates,
        winit::Key::Alphanumeric => Key::Alphanumeric,
        winit::Key::CodeInput => Key::CodeInput,
        winit::Key::Compose => Key::Compose,
        winit::Key::Convert => Key::Convert,
        winit::Key::FinalMode => Key::FinalMode,
        winit::Key::GroupFirst => Key::GroupFirst,
        winit::Key::GroupLast => Key::GroupLast,
        winit::Key::GroupNext => Key::GroupNext,
        winit::Key::GroupPrevious => Key::GroupPrevious,
        winit::Key::ModeChange => Key::ModeChange,
        winit::Key::NextCandidate => Key::NextCandidate,
        winit::Key::NonConvert => Key::NonConvert,
        winit::Key::PreviousCandidate => Key::PreviousCandidate,
        winit::Key::Process => Key::Process,
        winit::Key::SingleCandidate => Key::SingleCandidate,
        winit::Key::HangulMode => Key::HangulMode,
        winit::Key::HanjaMode => Key::HanjaMode,
        winit::Key::JunjaMode => Key::JunjaMode,
        winit::Key::Eisu => Key::Eisu,
        winit::Key::Hankaku => Key::Hankaku,
        winit::Key::Hiragana => Key::Hiragana,
        winit::Key::HiraganaKatakana => Key::HiraganaKatakana,
        winit::Key::KanaMode => Key::KanaMode,
        winit::Key::KanjiMode => Key::KanjiMode,
        winit::Key::Katakana => Key::Katakana,
        winit::Key::Romaji => Key::Romaji,
        winit::Key::Zenkaku => Key::Zenkaku,
        winit::Key::ZenkakuHankaku => Key::ZenkakuHankaku,
        winit::Key::Soft1 => Key::Soft1,
        winit::Key::Soft2 => Key::Soft2,
        winit::Key::Soft3 => Key::Soft3,
        winit::Key::Soft4 => Key::Soft4,
        winit::Key::ChannelDown => Key::ChannelDown,
        winit::Key::ChannelUp => Key::ChannelUp,
        winit::Key::Close => Key::Close,
        winit::Key::MailForward => Key::MailForward,
        winit::Key::MailReply => Key::MailReply,
        winit::Key::MailSend => Key::MailSend,
        winit::Key::MediaClose => Key::MediaClose,
        winit::Key::MediaFastForward => Key::MediaFastForward,
        winit::Key::MediaPause => Key::MediaPause,
        winit::Key::MediaPlay => Key::MediaPlay,
        winit::Key::MediaPlayPause => Key::MediaPlayPause,
        winit::Key::MediaRecord => Key::MediaRecord,
        winit::Key::MediaRewind => Key::MediaRewind,
        winit::Key::MediaStop => Key::MediaStop,
        winit::Key::MediaTrackNext => Key::MediaTrackNext,
        winit::Key::MediaTrackPrevious => Key::MediaTrackPrevious,
        winit::Key::New => Key::New,
        winit::Key::Open => Key::Open,
        winit::Key::Print => Key::Print,
        winit::Key::Save => Key::Save,
        winit::Key::SpellCheck => Key::SpellCheck,
        winit::Key::Key11 => Key::Key11,
        winit::Key::Key12 => Key::Key12,
        winit::Key::AudioBalanceLeft => Key::AudioBalanceLeft,
        winit::Key::AudioBalanceRight => Key::AudioBalanceRight,
        winit::Key::AudioBassBoostDown => Key::AudioBassBoostDown,
        winit::Key::AudioBassBoostToggle => Key::AudioBassBoostToggle,
        winit::Key::AudioBassBoostUp => Key::AudioBassBoostUp,
        winit::Key::AudioFaderFront => Key::AudioFaderFront,
        winit::Key::AudioFaderRear => Key::AudioFaderRear,
        winit::Key::AudioSurroundModeNext => Key::AudioSurroundModeNext,
        winit::Key::AudioTrebleDown => Key::AudioTrebleDown,
        winit::Key::AudioTrebleUp => Key::AudioTrebleUp,
        winit::Key::AudioVolumeDown => Key::AudioVolumeDown,
        winit::Key::AudioVolumeUp => Key::AudioVolumeUp,
        winit::Key::AudioVolumeMute => Key::AudioVolumeMute,
        winit::Key::MicrophoneToggle => Key::MicrophoneToggle,
        winit::Key::MicrophoneVolumeDown => Key::MicrophoneVolumeDown,
        winit::Key::MicrophoneVolumeUp => Key::MicrophoneVolumeUp,
        winit::Key::MicrophoneVolumeMute => Key::MicrophoneVolumeMute,
        winit::Key::SpeechCorrectionList => Key::SpeechCorrectionList,
        winit::Key::SpeechInputToggle => Key::SpeechInputToggle,
        winit::Key::LaunchApplication1 => Key::LaunchApplication1,
        winit::Key::LaunchApplication2 => Key::LaunchApplication2,
        winit::Key::LaunchCalendar => Key::LaunchCalendar,
        winit::Key::LaunchContacts => Key::LaunchContacts,
        winit::Key::LaunchMail => Key::LaunchMail,
        winit::Key::LaunchMediaPlayer => Key::LaunchMediaPlayer,
        winit::Key::LaunchMusicPlayer => Key::LaunchMusicPlayer,
        winit::Key::LaunchPhone => Key::LaunchPhone,
        winit::Key::LaunchScreenSaver => Key::LaunchScreenSaver,
        winit::Key::LaunchSpreadsheet => Key::LaunchSpreadsheet,
        winit::Key::LaunchWebBrowser => Key::LaunchWebBrowser,
        winit::Key::LaunchWebCam => Key::LaunchWebCam,
        winit::Key::LaunchWordProcessor => Key::LaunchWordProcessor,
        winit::Key::BrowserBack => Key::BrowserBack,
        winit::Key::BrowserFavorites => Key::BrowserFavorites,
        winit::Key::BrowserForward => Key::BrowserForward,
        winit::Key::BrowserHome => Key::BrowserHome,
        winit::Key::BrowserRefresh => Key::BrowserRefresh,
        winit::Key::BrowserSearch => Key::BrowserSearch,
        winit::Key::BrowserStop => Key::BrowserStop,
        winit::Key::AppSwitch => Key::AppSwitch,
        winit::Key::Call => Key::Call,
        winit::Key::Camera => Key::Camera,
        winit::Key::CameraFocus => Key::CameraFocus,
        winit::Key::EndCall => Key::EndCall,
        winit::Key::GoBack => Key::GoBack,
        winit::Key::GoHome => Key::GoHome,
        winit::Key::HeadsetHook => Key::HeadsetHook,
        winit::Key::LastNumberRedial => Key::LastNumberRedial,
        winit::Key::Notification => Key::Notification,
        winit::Key::MannerMode => Key::MannerMode,
        winit::Key::VoiceDial => Key::VoiceDial,
        winit::Key::TV => Key::TV,
        winit::Key::TV3DMode => Key::TV3DMode,
        winit::Key::TVAntennaCable => Key::TVAntennaCable,
        winit::Key::TVAudioDescription => Key::TVAudioDescription,
        winit::Key::TVAudioDescriptionMixDown => Key::TVAudioDescriptionMixDown,
        winit::Key::TVAudioDescriptionMixUp => Key::TVAudioDescriptionMixUp,
        winit::Key::TVContentsMenu => Key::TVContentsMenu,
        winit::Key::TVDataService => Key::TVDataService,
        winit::Key::TVInput => Key::TVInput,
        winit::Key::TVInputComponent1 => Key::TVInputComponent1,
        winit::Key::TVInputComponent2 => Key::TVInputComponent2,
        winit::Key::TVInputComposite1 => Key::TVInputComposite1,
        winit::Key::TVInputComposite2 => Key::TVInputComposite2,
        winit::Key::TVInputHDMI1 => Key::TVInputHDMI1,
        winit::Key::TVInputHDMI2 => Key::TVInputHDMI2,
        winit::Key::TVInputHDMI3 => Key::TVInputHDMI3,
        winit::Key::TVInputHDMI4 => Key::TVInputHDMI4,
        winit::Key::TVInputVGA1 => Key::TVInputVGA1,
        winit::Key::TVMediaContext => Key::TVMediaContext,
        winit::Key::TVNetwork => Key::TVNetwork,
        winit::Key::TVNumberEntry => Key::TVNumberEntry,
        winit::Key::TVPower => Key::TVPower,
        winit::Key::TVRadioService => Key::TVRadioService,
        winit::Key::TVSatellite => Key::TVSatellite,
        winit::Key::TVSatelliteBS => Key::TVSatelliteBS,
        winit::Key::TVSatelliteCS => Key::TVSatelliteCS,
        winit::Key::TVSatelliteToggle => Key::TVSatelliteToggle,
        winit::Key::TVTerrestrialAnalog => Key::TVTerrestrialAnalog,
        winit::Key::TVTerrestrialDigital => Key::TVTerrestrialDigital,
        winit::Key::TVTimer => Key::TVTimer,
        winit::Key::AVRInput => Key::AVRInput,
        winit::Key::AVRPower => Key::AVRPower,
        winit::Key::ColorF0Red => Key::ColorF0Red,
        winit::Key::ColorF1Green => Key::ColorF1Green,
        winit::Key::ColorF2Yellow => Key::ColorF2Yellow,
        winit::Key::ColorF3Blue => Key::ColorF3Blue,
        winit::Key::ColorF4Grey => Key::ColorF4Grey,
        winit::Key::ColorF5Brown => Key::ColorF5Brown,
        winit::Key::ClosedCaptionToggle => Key::ClosedCaptionToggle,
        winit::Key::Dimmer => Key::Dimmer,
        winit::Key::DisplaySwap => Key::DisplaySwap,
        winit::Key::DVR => Key::DVR,
        winit::Key::Exit => Key::Exit,
        winit::Key::FavoriteClear0 => Key::FavoriteClear0,
        winit::Key::FavoriteClear1 => Key::FavoriteClear1,
        winit::Key::FavoriteClear2 => Key::FavoriteClear2,
        winit::Key::FavoriteClear3 => Key::FavoriteClear3,
        winit::Key::FavoriteRecall0 => Key::FavoriteRecall0,
        winit::Key::FavoriteRecall1 => Key::FavoriteRecall1,
        winit::Key::FavoriteRecall2 => Key::FavoriteRecall2,
        winit::Key::FavoriteRecall3 => Key::FavoriteRecall3,
        winit::Key::FavoriteStore0 => Key::FavoriteStore0,
        winit::Key::FavoriteStore1 => Key::FavoriteStore1,
        winit::Key::FavoriteStore2 => Key::FavoriteStore2,
        winit::Key::FavoriteStore3 => Key::FavoriteStore3,
        winit::Key::Guide => Key::Guide,
        winit::Key::GuideNextDay => Key::GuideNextDay,
        winit::Key::GuidePreviousDay => Key::GuidePreviousDay,
        winit::Key::Info => Key::Info,
        winit::Key::InstantReplay => Key::InstantReplay,
        winit::Key::Link => Key::Link,
        winit::Key::ListProgram => Key::ListProgram,
        winit::Key::LiveContent => Key::LiveContent,
        winit::Key::Lock => Key::Lock,
        winit::Key::MediaApps => Key::MediaApps,
        winit::Key::MediaAudioTrack => Key::MediaAudioTrack,
        winit::Key::MediaLast => Key::MediaLast,
        winit::Key::MediaSkipBackward => Key::MediaSkipBackward,
        winit::Key::MediaSkipForward => Key::MediaSkipForward,
        winit::Key::MediaStepBackward => Key::MediaStepBackward,
        winit::Key::MediaStepForward => Key::MediaStepForward,
        winit::Key::MediaTopMenu => Key::MediaTopMenu,
        winit::Key::NavigateIn => Key::NavigateIn,
        winit::Key::NavigateNext => Key::NavigateNext,
        winit::Key::NavigateOut => Key::NavigateOut,
        winit::Key::NavigatePrevious => Key::NavigatePrevious,
        winit::Key::NextFavoriteChannel => Key::NextFavoriteChannel,
        winit::Key::NextUserProfile => Key::NextUserProfile,
        winit::Key::OnDemand => Key::OnDemand,
        winit::Key::Pairing => Key::Pairing,
        winit::Key::PinPDown => Key::PinPDown,
        winit::Key::PinPMove => Key::PinPMove,
        winit::Key::PinPToggle => Key::PinPToggle,
        winit::Key::PinPUp => Key::PinPUp,
        winit::Key::PlaySpeedDown => Key::PlaySpeedDown,
        winit::Key::PlaySpeedReset => Key::PlaySpeedReset,
        winit::Key::PlaySpeedUp => Key::PlaySpeedUp,
        winit::Key::RandomToggle => Key::RandomToggle,
        winit::Key::RcLowBattery => Key::RcLowBattery,
        winit::Key::RecordSpeedNext => Key::RecordSpeedNext,
        winit::Key::RfBypass => Key::RfBypass,
        winit::Key::ScanChannelsToggle => Key::ScanChannelsToggle,
        winit::Key::ScreenModeNext => Key::ScreenModeNext,
        winit::Key::Settings => Key::Settings,
        winit::Key::SplitScreenToggle => Key::SplitScreenToggle,
        winit::Key::STBInput => Key::STBInput,
        winit::Key::STBPower => Key::STBPower,
        winit::Key::Subtitle => Key::Subtitle,
        winit::Key::Teletext => Key::Teletext,
        winit::Key::VideoModeNext => Key::VideoModeNext,
        winit::Key::Wink => Key::Wink,
        winit::Key::ZoomToggle => Key::ZoomToggle,
        winit::Key::F1 => Key::F1,
        winit::Key::F2 => Key::F2,
        winit::Key::F3 => Key::F3,
        winit::Key::F4 => Key::F4,
        winit::Key::F5 => Key::F5,
        winit::Key::F6 => Key::F6,
        winit::Key::F7 => Key::F7,
        winit::Key::F8 => Key::F8,
        winit::Key::F9 => Key::F9,
        winit::Key::F10 => Key::F10,
        winit::Key::F11 => Key::F11,
        winit::Key::F12 => Key::F12,
        winit::Key::F13 => Key::F13,
        winit::Key::F14 => Key::F14,
        winit::Key::F15 => Key::F15,
        winit::Key::F16 => Key::F16,
        winit::Key::F17 => Key::F17,
        winit::Key::F18 => Key::F18,
        winit::Key::F19 => Key::F19,
        winit::Key::F20 => Key::F20,
        winit::Key::F21 => Key::F21,
        winit::Key::F22 => Key::F22,
        winit::Key::F23 => Key::F23,
        winit::Key::F24 => Key::F24,
        winit::Key::F25 => Key::F25,
        winit::Key::F26 => Key::F26,
        winit::Key::F27 => Key::F27,
        winit::Key::F28 => Key::F28,
        winit::Key::F29 => Key::F29,
        winit::Key::F30 => Key::F30,
        winit::Key::F31 => Key::F31,
        winit::Key::F32 => Key::F32,
        winit::Key::F33 => Key::F33,
        winit::Key::F34 => Key::F34,
        winit::Key::F35 => Key::F35,
        _ => todo!(),
    }
}

fn map_native_key(key: winit::NativeKey) -> NativeKey {
    match key {
        winit::NativeKey::Unidentified => NativeKey::Unidentified,
        winit::NativeKey::Android(k) => NativeKey::Android(k),
        winit::NativeKey::MacOS(k) => NativeKey::MacOS(k),
        winit::NativeKey::Windows(k) => NativeKey::Windows(k),
        winit::NativeKey::Xkb(k) => NativeKey::Xkb(k),
        winit::NativeKey::Web(k) => NativeKey::Web(k),
    }
}

fn map_key_location(location: winit::KeyLocation) -> KeyLocation {
    match location {
        winit::KeyLocation::Standard => KeyLocation::Standard,
        winit::KeyLocation::Left => KeyLocation::Left,
        winit::KeyLocation::Right => KeyLocation::Right,
        winit::KeyLocation::Numpad => KeyLocation::Numpad,
    }
}

fn map_modifiers(modifiers: winit::Modifiers) -> Modifiers {
    let mut state = ModifierState::default();
    if modifiers.state().shift_key() {
        state |= ModifierState::SHIFT;
    }
    if modifiers.state().alt_key() {
        state |= ModifierState::ALT;
    }
    if modifiers.state().control_key() {
        state |= ModifierState::CTRL;
    }
    if modifiers.state().super_key() {
        state |= ModifierState::SUPER;
    }

    let mut keys = ModifierKeys::default();
    if modifiers.lshift_state() == ModifiersKeyState::Pressed {
        keys |= ModifierKeys::LSHIFT;
    }
    if modifiers.rshift_state() == ModifiersKeyState::Pressed {
        keys |= ModifierKeys::RSHIFT;
    }
    if modifiers.lalt_state() == ModifiersKeyState::Pressed {
        keys |= ModifierKeys::LALT;
    }
    if modifiers.ralt_state() == ModifiersKeyState::Pressed {
        keys |= ModifierKeys::RALT;
    }
    if modifiers.lsuper_state() == ModifiersKeyState::Pressed {
        keys |= ModifierKeys::LSUPER;
    }
    if modifiers.rsuper_state() == ModifiersKeyState::Pressed {
        keys |= ModifierKeys::RSUPER;
    }
    if modifiers.lcontrol_state() == ModifiersKeyState::Pressed {
        keys |= ModifierKeys::LCTRL;
    }
    if modifiers.rcontrol_state() == ModifiersKeyState::Pressed {
        keys |= ModifierKeys::RCTRL;
    }

    Modifiers { state, keys }
}
